### ISSUE TITLE
The icon doesn't look good with dark theme

### ISSUE THREAD

**Issue by MarcAnt01** [stgeorgesepiscopal/google-meet-grid-view-extension#11]
![image](https://user-images.githubusercontent.com/43090263/78658987-33255400-78cb-11ea-84ff-0b10698ba70b.png)

**Comment by Cliabhach** [comment]
Since https://bugs.chromium.org/p/chromium/issues/detail?id=893175 is still open, I think the best solution would be to put a white outline around the boxes.

I made [a version of that kind of image with SVG](https://gist.github.com/Cliabhach/7dd3213669ec7066f0178d07fa3cbd01). Don't know how to make it work in the manifest; perhaps someone who understands image conversion can turn it into correctly-sized PNGs?
